stages:
  - build
build:
  stage: build
  image: gradle:6.1-jdk11
  script:
  - echo Build
  #change Directory to the Gradle main directory
  - cd messaging
  - gradle assemble
  only:
    refs:
    - 17-CI-Pipline
    - master
    - development
